### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by imbaah**

### CODE REVIEW

**Comment by danbjoseph** [comment]
1. can you please describe what has changed. is the logo different or just the file types?
2. so, the stacked type logo and just the icon w no text are no longer accepted formats?
3. i think it would be good to provide a template for the local customization (with the smaller "Missing Maps" and a third line that can be change to the place name)
4. previously, each version of the logo was provided in jpg, png, eps, and svg - this pull request just has pdf and png - will that be enough for all users?
5. is it intended that all the old files will be removed as part of this change?
Screen Shot 2022-10-27 at 8 46 17 AM

**Comment by imbaah** [comment]
1. What changed in the logo is the symbol > The circular section with its coloured fragments has white in the old logo and is transparent now. The colour definitions along with the distance between the symbol and the typography have also been "reminded". Here's an example of how it varied 
image
2. As part of Missing Maps visual identity, we use the full version of the logotype, which includes the symbol, circular section of coloured fragments and typography. This version is to be used in all offline materials and in print. The use of only the circular logo on online platforms is acceptable. Although, the user should weight whether the audience will know what it represents. If it is for a mapper group, the symbol should suffice but for a wide public, full version should be used.
- What does stacked type logo mean?
3. Excellent point, thank you Dan.
4. The formats I've shared are pdf, png and svg except for the logo with the white typography which is missing its svg format and I will add it as soon as I receive it. svg should be enough with its high resolution so I don't see the need of eps.
5. Yes I was planning on removing them but only after we add all the new ones.

> Jana will do a presentation of the logo manual tomorrow 1/11 during the ops call if you'd like to hear more about it. We can have a quick call too if you can't make it.

**Comment by imbaah** [comment]
Added logo with only its symbol and deleted the old ones.

**Comment by danbjoseph** [comment]
is this complete and ready to be merged?

**Comment by imbaah** [comment]
Yes it is! Thank you Dan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
